# Configuración de Netlify
[build]
  # Comando de construcción, el que usas para construir tu proyecto
  command = "npm run build"
  # Directorio de publicación donde Netlify buscará los archivos construidos
  publish = "build"

  # Versión de Node.js que quieres usar
  node_version = "18"  

[build.environment]
  NODE_ENV = "production"
  NODE_VERSION = "18"
